

[tasks.release]
description = "Run docgen and then support/release.cmd (Windows)"
script = [
    "cargo make docgen",
    "cmd /C support\\release.cmd"
]
workspace = false

[tasks.docgen]
description = "Generate README.md using docgen binary"
command = "cargo"
args = ["run", "--manifest-path", "uxn-tal-defined/docgen/Cargo.toml"]
workspace = false
cwd = "."