# Build, run Clippy, and test (native only) across all platforms
name: Check

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings

jobs:
  test:
    strategy:
      matrix:
        target: [
          # "ubuntu-24.04-arm", # disabled due to unreliability
          "ubuntu-latest",
          "windows-latest",
          "macos-14",
        ]
    runs-on: ${{ matrix.target }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-test
    - if: runner.os == 'Linux'
      name: Install  libudev-dev libxcb1-dev libasound2-dev
      run: sudo apt-get update && sudo apt-get install -y  libudev-dev libxcb1-dev libasound2-dev
      shell: bash
    - name: Test
      run: cargo test --release --verbose
  clippy:
    strategy:
      matrix:
        target: [
          # "ubuntu-24.04-arm", # disabled due to unreliability
          "ubuntu-latest",
          "windows-latest",
          "macos-14",
        ]
    runs-on: ${{ matrix.target }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-clippy
    - if: runner.os == 'Linux'
      name: Install libudev-dev and libxcb1-dev
      run: sudo apt-get update && sudo apt-get install -y libudev-dev libxcb1-dev libasound2-dev
      shell: bash
    - name: Clippy
      run: cargo clippy --all-targets --verbose
  wasm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-wasm
    - name: Install wasm target
      run: rustup target add wasm32-unknown-unknown
    - name: Clippy
      run: cargo clippy --target=wasm32-unknown-unknown -pcardinal-gui
    - name: Build
      env:
        RUSTFLAGS: "--cfg getrandom_backend=\"wasm_js\""
      run: cargo build --target=wasm32-unknown-unknown -pcardinal-gui
